# Generated by Django 3.2.4 on 2021-06-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210621_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('desc', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='expense',
            name='desc',
        ),
    ]
