# Generated by Django 3.2.4 on 2021-06-21 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210621_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comp_detail',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='desc',
        ),
        migrations.CreateModel(
            name='Desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('desc', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('user1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.expense')),
            ],
        ),
    ]
