# Generated by Django 3.2.4 on 2021-06-21 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210621_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desc',
            name='user1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.comp_detail'),
        ),
    ]
