# Generated by Django 3.2.4 on 2021-06-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_desc_user1'),
    ]

    operations = [
        migrations.AddField(
            model_name='desc',
            name='type1',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
    ]
