# Generated by Django 3.2.4 on 2021-06-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210622_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp_detail',
            name='balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='comp_detail',
            name='expense',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='comp_detail',
            name='income',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
