# Generated by Django 3.2.4 on 2021-08-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_desc_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desc',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
